### ISSUE TITLE
Glyph of Deposition's irises rotate specularly

### ISSUE THREAD

**Issue by ItsKazyan** [icwass/ReductiveMetallurgy#1]
Line 297 of glyphs.cs...

`drawPartGraphicSpecular(renderer, irisFullArray[index], textureCenter(irisFullArray[index]), 0f, hexGraphicalOffset(hex), Vector2.Zero);`

...causes rotation from specular lighting to be applied to the Glyph of Deposition's irises; this does not occur for any irises in the base game. The line should instead read:  

`drawPartGraphic(renderer, irisFullArray[index], textureCenter(irisFullArray[index]), 0f, hexGraphicalOffset(hex), Vector2.Zero);`

The specular lightning difference is hard to spot.

![image](https://github.com/icwass/ReductiveMetallurgy/assets/50607817/09254b74-f439-4267-bfae-5e0fb1f787ff)

**Comment by icwass** [comment]
This drawing behavior matches the Glyph of Purification, which also has the same bug:
![image](https://github.com/icwass/ReductiveMetallurgy/assets/64374645/7ee6f667-feef-43c9-a4e0-1a23c1d30c19)

(screenshot taken from the unmodded vanilla game)

**Comment by icwass** [comment]
Still, the visual oddity exists - I'll get that cleaned up. Maybe I'll clean up the vanilla part as well in Quintessential or something.

**Comment by icwass** [comment]
Fixed.
